{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "signals-platform.fullname" . }}-apps
  labels:
    app.kubernetes.io/name: {{ include "signals-platform.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  selector:
    matchExpressions:
      - key: app.kubernetes.io/instance
        operator: In
        values:
          - {{ .Release.Name | quote }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
{{- end }}
